[nfs]
172.31.63.45 ansible_ssh_user='ec2-user'

[webservers]
172.31.56.44 ansible_ssh_user='ec2-user'
172.31.63.7 ansible_ssh_user='ec2-user'

[db]
172.31.52.220 ansible_ssh_user='ec2-user' 

[lb]
172.31.55.183 ansible_ssh_user='ubuntu' 