---
- name: import common file  
  import_playbook: ../static-assignments/common.yml 
  tags:
    - always

- name: import common file  
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Database file
  import_playbook: ../static-assignments/db.yml

- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required 

