---
- name: Install JFrog Artifactory OSS
  hosts: all
  become: true
  tasks:
    - name: Download JFrog Artifactory RPM repository configuration
      get_url:
        url: "https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo"
        dest: "/etc/yum.repos.d/jfrog-artifactory-rpms.repo"

    - name: Update YUM cache and install JFrog Artifactory OSS
      yum:
        name: jfrog-artifactory-oss
        state: present

    - name: Enable Artifactory service at boot time
      systemd:
        name: artifactory.service
        enabled: yes

    - name: Start Artifactory service
      systemd:
        name: artifactory.service
        state: started

    - name: Check Artifactory service status
      systemd:
        name: artifactory.service
        state: status
